modules/*/config/oauth.yml:
  class:    sfOauthServerConfigHandler
  file: %SF_PLUGINS_DIR%/sfOauthPropelServerPlugin/config/sfOauthServerConfigHandler.class.php

config/filters.yml:
  class: sfOauthServerConfigFilterHandler
  file: %SF_PLUGINS_DIR%/sfOauthPropelServerPlugin/config/sfOauthServerConfigFilterHandler.class.php
